### ISSUE TITLE
[epic] Version 0.12 / Fall 2018 Re-Org

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#293]
There is a load of work to do to get ready for the Fall 2018 development cycle. Because we will be releasing so many changes, we are going to skip version 0.11 and release 0.12 (WALSTIB). 0.12 will break semver and contain serious breaking changes, including API v6. All APIs will be considered unstable until version 1.0, expected around December 2018.

The theme of this epic will be merging in all of the work that has been done over the past year towards the new platform, and reorging everything back into this repository. Managing releases and synchronizing changes across multiple repos has proven to be too tedious.

This epic consists of the following tasks:
- [ ] API v6
  - [x] Merge in and finish @razerater's work on API v6 and multi-semester schema
  - [x] Create common angular service for API v6 client
  - [ ] Update Malg to work with multi-semester model
  - [x] Document new API and Malg interface for NYU devs
  - [ ] Create schedules API v6
- [x] Merge in @sydtaylo's work on the improved UI and 
- [ ] Add missing sharing features (ICS download)
- [ ] Fix schedule navigation
- [ ] ~Users~ (pushed back to 0.13.0)
  - [ ] ~Write user data storage API~
  - [ ] ~Finish Auth library~
  - [ ] ~Create common angular users/storage service~
  - [ ] ~Refactor persistent angular services to use user storage service when logged in~
- [ ] Logging
  - [ ] Add sensible logging to core, malg, and users
  - [ ] Add logging stack
  - [ ] Add real performance monitoring
- [ ] Maintenance
  - [x] Finish yacs.io static site
  - [x] Add issue templates
  - [x] Add and document labeling system
  - [ ] Update README(s)
