### ISSUE TITLE
Rust Scheduler Service

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#307]
This epic is to create a new service to handle generating scheduled. It will be written in Rust, and will address the shortcomings of the old ruby scheduler, which currently lives in [core](https://github.com/YACS-RCOS/yacs/blob/master/lib/scheduler.rb).

Design Goals:
- Performant, parallel
  - TODO: Define how performant is acceptable
- Should respond to a HTTP endpoint

Data Model [WIP]:
- Schedulable
  - Has Many SchedulableOptions
  - e.g., Listing
  - Attributes
    - uuid
    - start (unix time)
   - duration (seconds since self.start)
- SchedulableOption
  - Has Many Events
  - e.g. Section
  - Attributes
    - uuid
- Event
  - Attributes:
    - uuid
    - start (seconds since schedulable.start)
    - duration (seconds since self.start)
    - repeat (seconds start to start)

Test cases:
- [ ] Current Case, strict weekly schedules
- [ ] strict two week schedules
- [ ] overlapping terms
- [ ] staggered events
  - [ ] weekly + biweekly
- [ ] One time events
