### ISSUE TITLE
Rust Scheduler Roadmap

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#346]
## Current State
- [ ] Defined data model
- [-] Created classes to represent data model
- [-] Serialization
- [-] Chose [Cassowary Constraint Solver](https://dylanede.github.io/cassowary-rs/cassowary/index.html)

## Roadmap
- [ ] Construct an instance of the solver populated with course data (11/5/18)
  - Should use the model we defined
- [ ] Take in arbitrary data and produce all perfect schedules (11/12/18)
  - [ ] Define any deficiencies in the model and document them
- [ ] Create Rust web server and api for generating schedules (11/19/18)
  - [ ] Actually pass in real schedule requests
  - [ ] Address deficiencies in the model
- [ ] Return "best" imperfect schedules when no perfect schedules are available (11/29/18)
