### ISSUE TITLE
Fix and Add Web Tests

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#349]
The tests for `web` need to be updated. We broke them when implementing API v6, and need to go back and update them. This should be fairly straightforward. Most of this will involve switching out references to the old models to the `yacs-api-client` models, and updating class names.

The following components have tests that need to be fixed:

- [ ] [`schedule-view`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/schedule-view/component.spec.ts)
- [ ] [`school-list`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/school-list/component.spec.ts)
- [ ] [`listing-view`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/listing-view/component.spec.ts)
- [ ] [`listing`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/listing/component.spec.ts)
- [ ] [`section`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/listing/section/component.spec.ts)
- [ ] [`header`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/header/component.spec.ts)

Additionally, the following components do not have tests and need tests to be added.

- [ ] [`schedule`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/schedule-view/schedule/component.ts)
- [ ] [`schedule-event`](https://github.com/YACS-RCOS/yacs/blob/feature/ui-overhaul/web/src/app/schedule-view/schedule-event/component.ts)
- [ ] [`school`](https://github.com/YACS-RCOS/yacs/tree/feature/ui-overhaul/web/src/app/school-list/school/component.ts)
- [ ] [`subject`](https://github.com/YACS-RCOS/yacs/tree/feature/ui-overhaul/web/src/app/school-list/subject/component.ts)

**Comment by Bad-Science** [comment]
We should probably have an issue for each one of these tests, and link those issues here, if someone wants to help out :P
